# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ludusapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_858b16811a9c492e85006505d3d4eba9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_86b348a0d07a4a3b878acb04edbd85ab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_858b16811a9c492e85006505d3d4eba9 }}/dudarts/ludus-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ludusapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e84c6290befd4534ad2c48545bf69cf1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_858b16811a9c492e85006505d3d4eba9 }}/dudarts/ludus-api:${{ github.sha }}'