# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ludusapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://luduscontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c02b137fb22244e4b20d9eeffa2b6c83 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ea0652039984e9c9268a62d64b14efe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: luduscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c02b137fb22244e4b20d9eeffa2b6c83 }}/ludus-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ludusapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_868f462b9ef04875b5ef9f5df9f9cd28 }}
        images: 'luduscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c02b137fb22244e4b20d9eeffa2b6c83 }}/ludus-api:${{ github.sha }}'